### ISSUE TITLE
GlobalVideo type not present

### ISSUE THREAD

**Issue by Hendicted** [GrowtopiaFli/openfl-haxeflixel-video-code#1]
![image](https://user-images.githubusercontent.com/36131469/118490881-bb0c9d00-b71e-11eb-93a3-c4c40b255933.png)

looked at the sources and i cant find anything about GlobalVideo, did you forget something or is it just me?

**Comment by edgardeivis** [comment]
Add the files in source to the fnf source folder

**Comment by Hendicted** [comment]
lol already did

**Comment by edgardeivis** [comment]
then i have no idea

**Comment by GrowtopiaFli** [comment]
its here
