### ISSUE TITLE
video keeps looping

### ISSUE THREAD

**Issue by dyaricoderman** [GrowtopiaFli/openfl-haxeflixel-video-code#12]
after my video is done and the game loads playstate, it just loads the video again so then i can't load into the song as the video is in an infinite loop

how do i fix this

h e l p

**Comment by GrowtopiaFli** [comment]
> after my video is done and the game loads playstate, it just loads the video again so then i can't load into the song as the video is in an infinite loop
> 
> how do i fix this
> 
> h e l p

send your code

**Comment by dyaricoderman** [comment]
> > after my video is done and the game loads playstate, it just loads the video again so then i can't load into the song as the video is in an infinite loop
> > how do i fix this
> > h e l p
> 
> send your code

i followed your exact instructions to set it up, and here is the code i used:
case 'test':
                    FlxG.switchState(new VideoState('assets/videos/testCutscene.webm', new PlayState()));

**Comment by GrowtopiaFli** [comment]
> > > after my video is done and the game loads playstate, it just loads the video again so then i can't load into the song as the video is in an infinite loop
> > > how do i fix this
> > > h e l p
> > 
> > 
> > send your code
> 
> i followed your exact instructions to set it up, and here is the code i used:
> case 'test':
> FlxG.switchState(new VideoState('assets/videos/testCutscene.webm', new PlayState()));

ya umm
i think you placed that in playstate am i right?
so of course it would loop
there is nothing to break that loop
you could try making a class and a public static variable called showcutscene or whatever
i can't really give you lectures on how to code

**Comment by dyaricoderman** [comment]
fixed, will now close this thread
