### ISSUE TITLE
The video plays, but then it crashes

### ISSUE THREAD

**Issue by mayo78** [GrowtopiaFli/openfl-haxeflixel-video-code#14]
So i got the video to work when i enter week1, but then when the video finishes, the game crashes with an error box saying `Null Object Reference`

**Comment by mayo78** [comment]
update: i recompiled the game and now the error box doesnt show up, the game just crashes

**Comment by Fefecomitre** [comment]
Same here. The video plays normally, but when it ends it says "kade engine exe has stopped working"

**Comment by GrowtopiaFli** [comment]
> So i got the video to work when i enter week1, but then when the video finishes, the game crashes with an error box saying `Null Object Reference`

send your code

**Comment by GrowtopiaFli** [comment]
Maybe You Used It Wrong
IM CLOSING THIS ISSUE
