### ISSUE TITLE
error when I compile the fnf game

### ISSUE THREAD

**Issue by icyboi223** [GrowtopiaFli/openfl-haxeflixel-video-code#15]
source/VideoState.hx:44: characters 26-41 : WebmHandler has no field SKIP_STEP_LIMIT

How do i fix this error?

**Comment by mayo78** [comment]
nab the VideoState.hx from the [Tricky Mod](https://github.com/KadeDev/trickster/)

**Comment by family1242** [comment]
It's some sort of error in the new files. Just do what mayo78 said.

**Comment by Fefecomitre** [comment]
hiya! i had the same problem. i found a way to fix it. all you gotta do is find wherever the webm library was installed ([haxe folder location]/lib/extension-webm/git/webm/WebmPlayer.hx) and change

static var SKIP_STEP_LIMIT = 0;
to

public static var SKIP_STEP_LIMIT = 0;
. that should help!

BIG THANKS AND CREDIT TO @dark279

https://github.com/dark279

**Comment by GrowtopiaFli** [comment]
> hiya! i had the same problem. i found a way to fix it. all you gotta do is find wherever the webm library was installed ([haxe folder location]/lib/extension-webm/git/webm/WebmPlayer.hx) and change
> 
> static var SKIP_STEP_LIMIT = 0;
> to
> 
> public static var SKIP_STEP_LIMIT = 0;
> . that should help!
> 
> BIG THANKS AND CREDIT TO @dark279
> 
> https://github.com/dark279

thats basically the current issue
do not use the extension-webm library from the tricky mod to compile my code that is updated
use MY extension-webm fork
which uhh
has conflicts with having public static var right now
