### ISSUE TITLE
Is every frame's sprite on top of every frame's sprite?

### ISSUE THREAD

**Issue by BugGlitchy64** [GrowtopiaFli/openfl-haxeflixel-video-code#17]
Hello! I'm making a mod which play videos as the background in PlayState, I did some good code editing but the problem is that the UI and characters at gone, tried everything but cannot bring them up on top of the video, so is every frame's sprite on top of every frame's sprite? If so... then how to fix this annoying issue? Searching on google on how to bring sprites up doesn't help me with much results.

**Comment by mayo78** [comment]
depending on what your background is, you could instead make a new stage (by copying the spooky background, editing it makes it so you can only have about 19 frames before it ends, but you can change the framerate to slow it down)

**Comment by BugGlitchy64** [comment]
> 
> 
> depending on what your background is, you could instead make a new stage (by copying the spooky background, editing it makes it so you can only have about 19 frames before it ends, but you can change the framerate to slow it down)

it would be a 2 minute video though, throught the chart

**Comment by GrowtopiaFli** [comment]
> Hello! I'm making a mod which play videos as the background in PlayState, I did some good code editing but the problem is that the UI and characters at gone, tried everything but cannot bring them up on top of the video, so is every frame's sprite on top of every frame's sprite? If so... then how to fix this annoying issue? Searching on google on how to bring sprites up doesn't help me with much results.

uhh
so basically this uses an OPENFL sprite
not a haxeflixel one
so sorry

**Comment by GrowtopiaFli** [comment]
> Hello! I'm making a mod which play videos as the background in PlayState, I did some good code editing but the problem is that the UI and characters at gone, tried everything but cannot bring them up on top of the video, so is every frame's sprite on top of every frame's sprite? If so... then how to fix this annoying issue? Searching on google on how to bring sprites up doesn't help me with much results.

also it doesnt do that
it just changes the pixels
of the OPENFL sprite
each frame
