### ISSUE TITLE
Video plays, but audio is slightly out of sync and is very glitchy!

### ISSUE THREAD

**Issue by BlazeGamesYT** [GrowtopiaFli/openfl-haxeflixel-video-code#19]
![image](https://user-images.githubusercontent.com/73793525/121826417-5f292b80-cc6c-11eb-9bb8-3dda1621ea3e.png)
https://youtu.be/Gt5Q2tx0AqI

Im playing the audio and its really glitchy and spams an error.

**Comment by GrowtopiaFli** [comment]
bring the whole log
your codec might be wrong
please specify the info above
just like
VP_9
or VP_8 
or something

**Comment by GrowtopiaFli** [comment]
Contact Me On Discord: GWebDev#3166

**Comment by Vinny-Lol** [comment]
I had an issue like this as well. I may need some help aswell

**Comment by ZEdasmoscas** [comment]
Im getting this error too

`                          Cluster Info
                Cluster Count   : 12

vorbis_synthesis failed, error: -136
vorbis_synthesis failed, error: -136
vorbis_synthesis failed, error: -136
vorbis_synthesis failed, error: -136

Bitstream not supported by this decoder`

**Comment by ZEdasmoscas** [comment]
> Im getting this error too
> 
> ` Cluster Info
> Cluster Count : 12
> 
> vorbis_synthesis failed, error: -136
> vorbis_synthesis failed, error: -136
> vorbis_synthesis failed, error: -136
> vorbis_synthesis failed, error: -136
> 
> Bitstream not supported by this decoder`

Can u please help me? I sent u a friend request in discord

Im </Guilherme.py>#0007 on discord

**Comment by GrowtopiaFli** [comment]
> Im getting this error too
> 
> ` Cluster Info
> Cluster Count : 12
> 
> vorbis_synthesis failed, error: -136
> vorbis_synthesis failed, error: -136
> vorbis_synthesis failed, error: -136
> vorbis_synthesis failed, error: -136
> 
> Bitstream not supported by this decoder`

u used vp9 webms
u must only use vp8
ucan see the log if it says vp8 or vp9
convet online or idk
