### ISSUE TITLE
[file_open,assets/videos/DO NOT DELETE OR GAME WILL CRASH/dontDelete.webm]

### ISSUE THREAD

**Issue by LeXS09** [GrowtopiaFli/openfl-haxeflixel-video-code#20]
This is making me lose my mind. idk why but this error pops up no matter what I do

**Comment by zatrit** [comment]
I got the same issue when I tried to run it on Android

**Comment by GrowtopiaFli** [comment]
> I got the same issue when I tried to run it on Android

sadly there is no solution for android yet
or idk
i hope someone does

**Comment by GrowtopiaFli** [comment]
also i dont know the cause of this issue
did you delete the file?

> This is making me lose my mind. idk why but this error pops up no matter what I do

**Comment by AdrianCD5** [comment]
This is also happening to me. Followed the guide, video is in the right folder, etc.

**Comment by GrowtopiaFli** [comment]
Can you guys contact my discord?
GWebDev#3166

> This is making me lose my mind. idk why but this error pops up no matter what I do



> I got the same issue when I tried to run it on Android



> This is also happening to me. Followed the guide, video is in the right folder, etc.

**Comment by GrowtopiaFli** [comment]
Remember 
Place <assets path code i sent in project.xml
ONLY IF YOU HAVE THE OLD FILE SYSTEM
DO I HAVE TO ADD THIS IN THE INSTRUCTIONS?
New File System Has The songs And preload Folder In The Assets Folder
If There Is A Folder Named Preload
Make A Folder In Preload Named videos
If Not Then Make A Folder In Assets Named videos And Add It To Project.xml
