### ISSUE TITLE
Compiling Game Problem with VideoState.hx

### ISSUE THREAD

**Issue by AllStarBreezy** [GrowtopiaFli/openfl-haxeflixel-video-code#21]
source/VideoState.hx:48: characters 31-46 : Cannot access static field SKIP_STEP_LIMIT from a class instance

im currently making a mod in fnf and im having an issue that it doesnt compile the game can anyone help me and solve this?

**Comment by GrowtopiaFli** [comment]
> source/VideoState.hx:48: characters 31-46 : Cannot access static field SKIP_STEP_LIMIT from a class instance
> 
> im currently making a mod in fnf and im having an issue that it doesnt compile the game can anyone help me and solve this?

you should try reinstalling my extension-webm fork
do not use the one from the tricky mod

**Comment by Behnja** [comment]
@GrowtopiaFli I have the same issue. I reinstalled your extension-webm and I still get the error "source/VideoState.hx:48: characters 31-46 : Cannot access static field SKIP_STEP_LIMIT from a class instance". Any idea of how to fix this?

**Comment by MrBxcx** [comment]
I have the same issue, I reinstalled the new extension-webm fork and still got the same error, and I have no idea how to fix it
