### ISSUE TITLE
error when recompile extension-webm using lime 

### ISSUE THREAD

**Issue by Tr1NgleBoss** [GrowtopiaFli/openfl-haxeflixel-video-code#27]
![image](https://user-images.githubusercontent.com/77019520/124263373-c0eefe00-db65-11eb-9fa1-e3600324b600.png)
help please

**Comment by Tr1NgleBoss** [comment]
and this error when i do second recompile
![image](https://user-images.githubusercontent.com/77019520/124263520-eda31580-db65-11eb-9b66-d8f7aa7bfaf5.png)

**Comment by GrowtopiaFli** [comment]
I Think You May Want To Not Use My Video Code
Because Your Environmental Resources Are Running Out
Just By Rebuilding A New NDLL
That Means Your CPU Or RAM Is Running Out Whenever You Rebuild

**Comment by GrowtopiaFli** [comment]
IDK what to say but just keep rebuilding until it finishes
if you want to contact me on discord:
GWebDev#3166
