### ISSUE TITLE
Error when build game 

### ISSUE THREAD

**Issue by Tr1NgleBoss** [GrowtopiaFli/openfl-haxeflixel-video-code#28]
![image](https://user-images.githubusercontent.com/77019520/124263977-86d22c00-db66-11eb-9676-1894d0cb2221.png)

**Comment by Tr1NgleBoss** [comment]
![image](https://user-images.githubusercontent.com/77019520/124264281-dc0e3d80-db66-11eb-8986-7a74a3bb8e60.png)
![image](https://user-images.githubusercontent.com/77019520/124264299-e2041e80-db66-11eb-83e6-d6fd2dbf7873.png)

**Comment by Tr1NgleBoss** [comment]
![image](https://user-images.githubusercontent.com/77019520/124264656-58088580-db67-11eb-9d6a-0198e50d8e86.png)

**Comment by GrowtopiaFli** [comment]
You Did Not Rebuild It
Please Think Before Making Issues Like This
lime rebuild extension-webm windows
