### ISSUE TITLE
error when rebuilding extension-webm for android

### ISSUE THREAD

**Issue by huma139** [GrowtopiaFli/openfl-haxeflixel-video-code#29]
Hello.

So I want to use this extension for android port but when I tried to `lime rebuild extension-webm android`, it shows this message and I don't know what to do. 

![image](https://user-images.githubusercontent.com/70441025/124639686-a8108080-deb6-11eb-9eb2-331a206233d6.png)

Note that I did run these commands before:
```
lime config HXCPP_ARM64 true
lime config HXCPP_x86 true
```
but it doesn't work.
Please help.

**Comment by GrowtopiaFli** [comment]
Contact me on discord:
GWebDev#3166
