### ISSUE TITLE
Question: Song specific cutscenes

### ISSUE THREAD

**Issue by edgardeivis** [GrowtopiaFli/openfl-haxeflixel-video-code#3]
FlxG.switchState(new VideoState('assets/videos/yoursourcevideo.webm');

how do i make song specific videos, i can't even explain i'm just tired as hell

**Comment by Fefecomitre** [comment]
https://www.youtube.com/watch?v=CKNfu8G9EOc&t=3s

**Comment by Fefecomitre** [comment]
oml sorry wrong video

**Comment by Fefecomitre** [comment]
https://www.youtube.com/watch?v=k67RvU6qI_Q&t=51s also booo agoti new song leak

**Comment by edgardeivis** [comment]
not song specific, just week specific

**Comment by Fefecomitre** [comment]
all in the video

**Comment by edgardeivis** [comment]
timestamp?

**Comment by Fefecomitre** [comment]
6:02

**Comment by edgardeivis** [comment]
i once again repeat, that's week specific, not song

**Comment by Fefecomitre** [comment]
Alr so 
1st: thanks for following
2nd: please explain the week specific

**Comment by edgardeivis** [comment]
Hi, i figured it out, no need to help me any further, thanks alot, that video did help a bit

**Comment by Fefecomitre** [comment]
Np

**Comment by trayfellow** [comment]
> Hi, i figured it out, no need to help me any further, thanks alot, that video did help a bit

how do you do it?

**Comment by Fefecomitre** [comment]
https://www.youtube.com/watch?v=k67RvU6qI_Q&t=51s 6:03

**Comment by trayfellow** [comment]
like edgar said, thats week specific, not song

**Comment by edgardeivis** [comment]
hi trayfellow, go to gamebanana and look for vs tree, then go to the source code, it should be there in the playstate.hx, just do ctrl + f and search revolution

**Comment by trayfellow** [comment]
> hi trayfellow, go to gamebanana and look for vs tree, then go to the source code, it should be there in the playstate.hx, just do ctrl + f and search revolution

thanks!

**Comment by mayo78** [comment]
i tried using some of the vs tree code but it didnt load when i went into the song (not using freeplay)
