### ISSUE TITLE
Cant use cutscenes, it just shows this.

### ISSUE THREAD

**Issue by OfficialMarzYT** [GrowtopiaFli/openfl-haxeflixel-video-code#30]
![image](https://user-images.githubusercontent.com/76492103/124953364-15213480-dfe3-11eb-961d-1e42b88e13a8.png)
It is a VP8 webm with 719 frames and i have no idea what i'm doing wrong.

**Comment by TrustVVorthy** [comment]
im having the same issue, but the current solutions aint working for me.
One of the solutions is to re-install extension-webm through growtopiaflis fork
but that did not work for me,

**Comment by OfficialMarzYT** [comment]
> im having the same issue, but the current solutions aint working for me.
> One of the solutions is to re-install extension-webm through growtopiaflis fork
> but that did not work for me,

same here i even tried messing with VideoState.hx but to no avail

**Comment by GrowtopiaFli** [comment]
> im having the same issue, but the current solutions aint working for me.
> One of the solutions is to re-install extension-webm through growtopiaflis fork
> but that did not work for me,

dude u did NOT reinstall it
i updated it but
u did NOT reinstall it
to do that
do
haxelib remove extension-webm
THEN install it with git and such
