### ISSUE TITLE
Game Crashes suddenly after like 1 month of working

### ISSUE THREAD

**Issue by LEON-BROTHER** [GrowtopiaFli/openfl-haxeflixel-video-code#32]
error:
Called from hxcpp::__hxcpp_main
Called from ApplicationMain::main ApplicationMain.hx line 25
Called from ApplicationMain::create ApplicationMain.hx line 130
Called from lime.app.Application::exec lime/app/Application.hx line 150
Called from lime._internal.backend.native.NativeApplication::exec lime/_internal/backend/native/NativeApplication.hx line 146
Called from lime._internal.backend.native.NativeApplication::handleRenderEvent lime/_internal/backend/native/NativeApplication.hx line 370
Called from lime.app._Event_lime_graphics_RenderContext_Void::dispatch lime/_internal/macros/EventMacro.hx line 91
Called from openfl.display.Stage::__onLimeRender openfl/display/Stage.hx line 1950
Called from openfl.display.Stage::__broadcastEvent openfl/display/Stage.hx line 1166
Called from openfl.display.DisplayObject::__dispatch openfl/display/DisplayObject.hx line 1399
Called from openfl.events.EventDispatcher::__dispatchEvent openfl/events/EventDispatcher.hx line 402
Called from webm.WebmPlayer::onSpriteEnterFrame webm/WebmPlayer.hx line 192
Called from webm.WebmPlayer::stepVideoFrame webm/WebmPlayer.hx line 207
Called from ŀtWMŤt6Eˎ8DɈ%::థXн  line 161
Called from webm.WebmPlayer::decodeVideoFrame webm/WebmPlayer.hx line 235
Called from webm.VpxDecoder::getAndRenderFrame webm/VpxDecoder.hx line 35
Error : Null Object Reference

code:

`PlayState.storyDifficulty = curDifficulty;

			PlayState.SONG = Song.loadFromJson(PlayState.storyPlaylist[0].toLowerCase() + diffic, PlayState.storyPlaylist[0].toLowerCase());
			PlayState.storyWeek = curWeek;
			PlayState.campaignScore = 0;
			if (curWeek == 7 && FlxG.save.data.week7Cut)
				new FlxTimer().start(1, function(tmr:FlxTimer)
				{
					LoadingState.loadAndSwitchState(new VideoState("videos/ughCutscene.webm", new PlayState()));
				});
			else
				new FlxTimer().start(1, function(tmr:FlxTimer)
				{
					LoadingState.loadAndSwitchState(new PlayState(), true);
				});`

**Comment by LEON-BROTHER** [comment]
its was already working but then its just crashing

**Comment by GrowtopiaFli** [comment]
BrightFyre has the same issue
i'm powerless here
does anyone know what the problem is?
my guess is that this had something to do with versions of the libraries like lime or openfl

**Comment by LEON-BROTHER** [comment]
Well I'm using Psych Engine so I think that this Issue is useless now ima close it
