### ISSUE TITLE
Cannot access static field SKIP_STEP_LIMIT from a class instance

### ISSUE THREAD

**Issue by TheGoldenPotion** [GrowtopiaFli/openfl-haxeflixel-video-code#33]
I'm compiling the game after following all the instructions in the README.md file but every time I compile I get this error.

Here's the code I've added:
`new FlxTimer().start(1, function(tmr:FlxTimer)`
`{`
`⠀⠀⠀if (curWeek == 0`
`⠀⠀⠀{`
`⠀⠀⠀⠀⠀⠀FlxG.switchState(new VideoState('assets/videos/cutscene.webm', new PlayState()));`
`⠀⠀⠀}`
`⠀⠀⠀else`
`⠀⠀⠀{`
`⠀⠀⠀⠀⠀⠀LoadingState.loadAndSwitchState(new PlayState(), true);`
`⠀⠀⠀}`
`});`

**Comment by GrowtopiaFli** [comment]
u have the kade engine extension-webm library installed and not mine
haxelib remove extension-webm
then read my instruction and do the haxelib git command in MY repository
and then do
lime rebuild extension-webm windows
it depends if you have a mac do mac
if linux linux
if u installed android studio and did
lime setup android
then do android

**Comment by TheGoldenPotion** [comment]
i have now just realised that there was a missing close parenthesis on curWeek == 0
