### ISSUE TITLE
Bitstream not supported by this decoder

### ISSUE THREAD

**Issue by TomAvecLeVdsl** [GrowtopiaFli/openfl-haxeflixel-video-code#34]
Hi, little issue, i've got all my files and video ni here but everytime i want them to play i get the "Bitstream not supported by this decoder" error, any ideas ?
Thanks

**Comment by ZEdasmoscas** [comment]
I have the same issue

**Comment by KouFan2250** [comment]
me too

**Comment by ZEdasmoscas** [comment]
So, you used vp9 webm when you should use vp8 webm, its that simple

**Comment by GrowtopiaFli** [comment]
this is a stupid question to be quite frank
i literally stated in the instructions
that you should use a vp8 webm
vp8 and vp9 are different bitstreams and vp9 wasnt coded in the codec
this should be a lesson to you
