### ISSUE TITLE
can't rebuild extension-webm on linux

### ISSUE THREAD

**Issue by 448L** [GrowtopiaFli/openfl-haxeflixel-video-code#35]
I'm a fool, I followed the steps.

![imagen](https://user-images.githubusercontent.com/60526375/127228591-9b8ffcb7-511c-4ed1-9419-dcb85471c940.png)

and when I try to rebuild it, I get this....

![imagen](https://user-images.githubusercontent.com/60526375/127228650-70d5f1ae-1818-4760-ad40-3e7e282cc525.png)

**Comment by 448L** [comment]
What, for some reason it worked, and I don't know why?

bruh, I think this repote was garbage.

**Comment by 448L** [comment]
What, for some reason it worked, and I don't know why?

bruh, I think this repote was garbage.

**Comment by GrowtopiaFli** [comment]
you had to do haxelib run lime
i updated my instructions
