### ISSUE TITLE
Audio is extremely broken.

### ISSUE THREAD

**Issue by Ombrezz** [GrowtopiaFli/openfl-haxeflixel-video-code#37]
When a video is playing, the audio is extremely slow, choppy, and out of sync with the video.  However this seems to only happen when the video is the selected element, when I built it in debug mode and clicked into the command prompt, the audio fixed, but when I clicked back to the video it broke again.  Any help would be greatly appreciated.

**Comment by GrowtopiaFli** [comment]
it depends on your system
someone wrote this codec and it isnt stable
you think i can code c++?
