### ISSUE TITLE
Compiling doesn’t work 

### ISSUE THREAD

**Issue by Pandaity** [GrowtopiaFli/openfl-haxeflixel-video-code#41]
Hi I thought you were supposed to put lime config HXCPP_ARM64 and HXCPP_x86
But I tried changing them to false and still doesn’t let me compile please help me I need to code but I can’t compile thanks.

**Comment by Pandaity** [comment]
![Uploading E62BE9EC-8BBC-4B91-8CAD-436EF4CC2E66.png…]()

**Comment by Pandaity** [comment]
![B23FEEB9-AE9F-4952-8EF9-65D3978FD6C9](https://user-images.githubusercontent.com/85077779/131573022-2ff72084-ca11-46a5-a75a-1a52b95fd09d.png)

**Comment by GrowtopiaFli** [comment]
umm
yeah no
i will send prebuilds
dont do that
do set it again
and make it 0
