### ISSUE TITLE
Game crashes upon launch

### ISSUE THREAD

**Issue by indigoUan** [GrowtopiaFli/openfl-haxeflixel-video-code#42]
when I launch the game after compiling it, it crashes immediately, and apparently has something to do with the dontDelete file, as the error message says [file_open,assets/videos/DO NOT DELETE OR GAME WILL CRASH/dontDelete.webm]

**Comment by GrowtopiaFli** [comment]
did you delete it

**Comment by indigoUan** [comment]
no lol

**Comment by ZhaneTheAnimater** [comment]
have you solved it yet

**Comment by indigoUan** [comment]
nope

**Comment by ZhaneTheAnimater** [comment]
did you put in the code that is suppose to go to the main file because if so remove the code because it crashes the game upon launch if you add the code

**Comment by indigoUan** [comment]
nevermind i fixed it
