### ISSUE TITLE
*Im an idiot so can someone help me become something that is not an idiot

### ISSUE THREAD

**Issue by ZhaneTheAnimater** [GrowtopiaFli/openfl-haxeflixel-video-code#43]
so I don't know why but I decided to run the lime config HXCPP_ARM64 true and lime config HXCPP_x86 true commands and now I can't compile my game anymore because it shows this in the cmd."obj\msvc19-arm64-nc\70e38311_Context3DElementType.obj : fatal error LNK1112: module machine type 'x64' conflicts with target machine type 'ARM64'". So can anyone help me turn it off or erase it completely because I really need to fix this problem as fast as I can?

**Comment by IndigoDarkw0lf** [comment]
I use visual studio code, not visual studio.

**Comment by tikycookies** [comment]
you have visual studio for arm64 install the intel one

**Comment by GrowtopiaFli** [comment]
> you have visual studio for arm64 install the intel one

Wrong basically
he set it to compile for machine types x86 or arm64
while his is 64 bit

**Comment by ZhaneTheAnimater** [comment]
so how do I remove the config also I was really bust and didn't have time time see this reply which is why I am asking now, how do I remove it.

**Comment by ZhaneTheAnimater** [comment]
when you asked the question why I need to do it its mostly for a cover I'm making but I wanted to use kade engine for it and I was using psych engine after 2 days of trying to find out how to fix this, and the reason why I ran the commands was because I was bored and thought nothing would happen when I ran these commands and was met with the scary error and yeah until now I decided to actually fix this time also thanks it actually somehow worked.
