### ISSUE TITLE
Video slows down along with the audio

### ISSUE THREAD

**Issue by IndigoDarkw0lf** [GrowtopiaFli/openfl-haxeflixel-video-code#5]
So, every time the video plays, I hear the audio working normally but the video is slowed down. When it reaches a certain point in the video, the audio repeats and slows down with the video.

https://user-images.githubusercontent.com/78701030/120113692-9ca89780-c149-11eb-84c7-36dd2d22e3b4.mp4

**Comment by IndigoDarkw0lf** [comment]
also, the audio being on the left channel is supposed to happen. don't worry about that.

**Comment by trayfellow** [comment]
happens to me too

**Comment by GrowtopiaFli** [comment]
> So, every time the video plays, I hear the audio working normally but the video is slowed down. When it reaches a certain point in the video, the audio repeats and slows down with the video.
> 
>  2021-05-30-13-16-25.mp4

actually your issue name is
Video slows down
because the audio synchronizes with the audio
since i placed that feature
idk how to fix this
either your computer's specifications
or the video being to heavy to decode on openfl
