### ISSUE TITLE
Not technically a issue, but a little Info

### ISSUE THREAD

**Issue by TheHENOOB** [GrowtopiaFli/openfl-haxeflixel-video-code#9]
I found a game which makes HaxeFlixel (OpenFL) run videos which is this game

Tankmas ADVENTure 2020
(GAME LINK) https://www.newgrounds.com/portal/view/773236
(GITHUB REPO) https://github.com/Geokureli/Advent2020
(Notes: I think you need a Newgrounds account to run this game)

if you go through the movies room you will see a little animation on newgrounds running in-game

This is the video code in game:
https://github.com/Geokureli/Advent2020/blob/master/source/states/VideoSubstate.hx

If you are using Flash for animation, is possible to make SWF files playable in OpenFL
https://www.openfl.org/learn/haxelib/tutorials/using-swf-assets/
I think it has a way to run on HaxeFlixel but right now i am finding a way

I hope this little info is helpful

**Comment by mayo78** [comment]
any updates?

**Comment by TheHENOOB** [comment]
> any updates?

I closed this issue because i discovered that openfl doesn't support video in the way it was made on ADVENT 2020 in the desktop target

The SWF way is possible but the problem is that it doesn't support tweens (like motion, shape, classic) everything should be frame by frame
